remote_theme: pages-themes/midnight@v0.2.0
plugins:
- Midnight
title: A short poetry
description: A metaphor that is always true when viewed from the lens of all the is Holy, is True. He is the Truth that was, is and is to come. Come, Lord. Amen!
